# We specify volumes in override.yml, because volumes don't work well in a
# docker-in-docker setup (the paths of parent host rarely match the nested containers)
version: "3.9"

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - app-db-data:/var/lib/postgresql/data:cached
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 3

  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file: .env
    command: uvicorn --port 8000 --host 0.0.0.0 --reload main:app
    volumes:
      - ./backend:/app:delegated
      - root-home:/root:delegated
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  app-db-data:
  root-home:
